using Avalonia.Controls;
using Avalonia.Controls.Templates;
using Avalonia.Media;
using System;

namespace Diffracta;

public partial class Utils_DirectoryBox : UserControl
{
    public Utils_DirectoryBox()
    {
        InitializeComponent();
        
        // Set up DirectoryListBox ItemTemplate with colored [DIR] text
        // Note: DirectoryListBox is auto-generated by Avalonia from x:Name in AXAML
        if (DirectoryListBox != null)
        {
            DirectoryListBox.ItemTemplate = new FuncDataTemplate<string>((item, _) =>
            {
                if (item != null && item.StartsWith("[DIR]"))
                {
                    // Create a horizontal stack panel with [DIR] in yellow and rest in white
                    var panel = new StackPanel 
                    { 
                        Orientation = Avalonia.Layout.Orientation.Horizontal,
                        VerticalAlignment = Avalonia.Layout.VerticalAlignment.Center
                    };
                    
                    var dirText = new TextBlock 
                    { 
                        Text = "[DIR]", 
                        Foreground = Brushes.Yellow,
                        FontSize = 12,
                        VerticalAlignment = Avalonia.Layout.VerticalAlignment.Center
                    };
                    
                    var rest = item.Substring(5).TrimStart();
                    var nameText = new TextBlock 
                    { 
                        Text = string.IsNullOrEmpty(rest) ? "" : " " + rest, 
                        Foreground = Brushes.White,
                        FontSize = 12,
                        VerticalAlignment = Avalonia.Layout.VerticalAlignment.Center
                    };
                    
                    panel.Children.Add(dirText);
                    panel.Children.Add(nameText);
                    
                    return panel;
                }
                else
                {
                    // Regular file, just white text
                    return new TextBlock 
                    { 
                        Text = item ?? "", 
                        Foreground = Brushes.White,
                        FontSize = 12,
                        VerticalAlignment = Avalonia.Layout.VerticalAlignment.Center
                    };
                }
            });
        }
    }
}

