using Avalonia.Controls;
using Avalonia.Controls.Templates;
using Avalonia.Media;
using System;

namespace Diffracta;

public partial class Utils_DirectoryBox : UserControl
{
    private MainWindow? _parentWindow;
    
    public Utils_DirectoryBox()
    {
        InitializeComponent();
        
        // Set up DirectoryListBox ItemTemplate with colored [DIR] text
        // Note: DirectoryListBox is auto-generated by Avalonia from x:Name in AXAML
        if (DirectoryListBox != null)
        {
            DirectoryListBox.ItemTemplate = new FuncDataTemplate<string>((item, _) =>
            {
                if (item != null && item.StartsWith("[DIR]"))
                {
                    // Create a horizontal stack panel with [DIR] in yellow and rest in white
                    var panel = new StackPanel 
                    { 
                        Orientation = Avalonia.Layout.Orientation.Horizontal,
                        VerticalAlignment = Avalonia.Layout.VerticalAlignment.Center
                    };
                    
                    var dirText = new TextBlock 
                    { 
                        Text = "[DIR]", 
                        Foreground = Brushes.Yellow,
                        FontSize = 12,
                        VerticalAlignment = Avalonia.Layout.VerticalAlignment.Center
                    };
                    
                    var rest = item.Substring(5).TrimStart();
                    var nameText = new TextBlock 
                    { 
                        Text = string.IsNullOrEmpty(rest) ? "" : " " + rest, 
                        Foreground = Brushes.White,
                        FontSize = 12,
                        VerticalAlignment = Avalonia.Layout.VerticalAlignment.Center
                    };
                    
                    panel.Children.Add(dirText);
                    panel.Children.Add(nameText);
                    
                    return panel;
                }
                else
                {
                    // Regular file, just white text
                    return new TextBlock 
                    { 
                        Text = item ?? "", 
                        Foreground = Brushes.White,
                        FontSize = 12,
                        VerticalAlignment = Avalonia.Layout.VerticalAlignment.Center
                    };
                }
            });
        }
    }
    
    /// <summary>
    /// Sets the parent MainWindow reference and wires up the AddToWatched button.
    /// </summary>
    public void SetParentWindow(MainWindow parent)
    {
        _parentWindow = parent;
        
        // Wire up the AddToWatched button - use FindControl as fallback if auto-generated field isn't available yet
        var addButton = this.FindControl<Button>("AddToWatchedButton");
        var pathTextBox = this.FindControl<TextBox>("DirectoryPathTextBox");
        
        if (addButton != null && pathTextBox != null)
        {
            addButton.Click += (_, __) =>
            {
                var currentPath = pathTextBox.Text?.Trim() ?? string.Empty;
                if (!string.IsNullOrWhiteSpace(currentPath) && System.IO.Directory.Exists(currentPath))
                {
                    _parentWindow?.AddMediaDirectory(currentPath);
                }
            };
        }
    }
}

